### ISSUE TITLE
GetAllClients?

### ISSUE THREAD

**Issue by zabiphillip** [vacoj/MINDBODY-Django#1]
Hi, I'm trying to do something similar like how you're getting every client, however when I try to get every client, I actually get no clients. I'm using an empty string under SearchText and did not put down anything under ClientIDs inside the Request... not sure what else I'm supposed to do?

**Comment by vacovsky** [comment]
It should work if you use https://github.com/vacoj/MINDBODY-Django/blob/master/web/servicecalls/clientservice_gets.py as the example.  Are you receiving any errors when you run the request, or just an empty result set?

**Comment by zabiphillip** [comment]
I'm unable to use the example directly, because I ultimately want to run something like it in php. I'm just getting an empty result set whenever I have the SearchText involved (null, empty or some string value). I am getting some clients by filling in with their client ids, but I'm unable to just simply get all the clients.

I have something like this right now,

https://gist.github.com/zabiphillip/29dbaa09c5d754f8ee00

**Comment by zabiphillip** [comment]
Also, pretty unrelated, but what I really would like is a way to get all MINDBODY sales, with information like the client id and sales item id related to each sale from GetSales. I haven't really found a way to do this since the result only seems to contain the sales id and the payment id... am I missing something?

**Comment by vacovsky** [comment]
I made an example request in XML for you to model your PHP off of.  This request returns all clients on a site. Just make sure you fill in all the necessary credentials (both source and user with site):

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:_5="http://clients.mindbodyonline.com/api/0_5">
   <soapenv:Header/>
   <soapenv:Body>
      <_5:GetClients>
         <_5:Request>
            <_5:SourceCredentials>
               <_5:SourceName></_5:SourceName>
               <_5:Password></_5:Password>
               <_5:SiteIDs>
                  <_5:int></_5:int>
               </_5:SiteIDs>
            </_5:SourceCredentials>
            <_5:UserCredentials>
               <_5:Username></_5:Username>
               <_5:Password></_5:Password>
               <_5:SiteIDs>
                  <_5:int></_5:int>
               </_5:SiteIDs>
            </_5:UserCredentials>
            <_5:XMLDetail>Full</_5:XMLDetail>
            <_5:PageSize>100</_5:PageSize>
            <_5:CurrentPageIndex>0</_5:CurrentPageIndex>
            <_5:SearchText></_5:SearchText>
         </_5:Request>
      </_5:GetClients>
   </soapenv:Body>
</soapenv:Envelope>
```
